export default {
  '018242a7': [() => import(/* webpackChunkName: '018242a7' */ '@site/docs/4-functional-programming/hometask.mdx'), '@site/docs/4-functional-programming/hometask.mdx', require.resolveWeak('@site/docs/4-functional-programming/hometask.mdx')],
  '045a5587': [() => import(/* webpackChunkName: '045a5587' */ '/Users/Ernest_Yedigaryan/Desktop/Ernest/JavaScript/software_design/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/Ernest_Yedigaryan/Desktop/Ernest/JavaScript/software_design/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/Ernest_Yedigaryan/Desktop/Ernest/JavaScript/software_design/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '368d136d': [() => import(/* webpackChunkName: '368d136d' */ '@site/docs/4-functional-programming/main_concepts.md'), '@site/docs/4-functional-programming/main_concepts.md', require.resolveWeak('@site/docs/4-functional-programming/main_concepts.md')],
  '3ded7021': [() => import(/* webpackChunkName: '3ded7021' */ '@site/docs/4-functional-programming/categories_and_functors.md'), '@site/docs/4-functional-programming/categories_and_functors.md', require.resolveWeak('@site/docs/4-functional-programming/categories_and_functors.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '800022a5': [() => import(/* webpackChunkName: '800022a5' */ '@site/docs/4-functional-programming/fp_introduction.md'), '@site/docs/4-functional-programming/fp_introduction.md', require.resolveWeak('@site/docs/4-functional-programming/fp_introduction.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'a94b9cf1': [() => import(/* webpackChunkName: 'a94b9cf1' */ '@site/docs/4-functional-programming/type_classes.md'), '@site/docs/4-functional-programming/type_classes.md', require.resolveWeak('@site/docs/4-functional-programming/type_classes.md')],
  'b04c6e8a': [() => import(/* webpackChunkName: 'b04c6e8a' */ '@site/docs/4-functional-programming/is_js_functional.md'), '@site/docs/4-functional-programming/is_js_functional.md', require.resolveWeak('@site/docs/4-functional-programming/is_js_functional.md')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'e04b78a4': [() => import(/* webpackChunkName: 'e04b78a4' */ '/Users/Ernest_Yedigaryan/Desktop/Ernest/JavaScript/software_design/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/Ernest_Yedigaryan/Desktop/Ernest/JavaScript/software_design/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/Ernest_Yedigaryan/Desktop/Ernest/JavaScript/software_design/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],};
